# Generated by Django 5.0.3 on 2024-04-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_productos', '0002_alter_producto_descripcion'),
        ('control_ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cliente',
            new_name='cajero',
        ),
        migrations.AddField(
            model_name='venta',
            name='Producto',
            field=models.ManyToManyField(through='control_ventas.DetalleVenta', to='control_productos.producto'),
        ),
    ]
