# Generated by Django 5.0.3 on 2024-04-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_ventas', '0002_rename_cliente_venta_cajero_venta_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cajero',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='Producto',
        ),
    ]
