# Generated by Django 5.0.3 on 2024-04-05 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ventas', '0011_alter_detalleventa_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='control_ventas.venta'),
        ),
    ]
