# Generated by Django 5.0.3 on 2024-05-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_productos', '0002_alter_producto_descripcion'),
        ('control_ventas', '0012_alter_detalleventa_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='control_productos.producto'),
        ),
    ]
