# Generated by Django 5.0.3 on 2024-05-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ventas', '0014_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Subtotal'),
        ),
    ]
