# Generated by Django 5.0.4 on 2024-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ventas', '0023_alter_detalleventa_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('entregado', 'Entregado'), ('cancelada', 'Cancelada')], default='en proceso', max_length=20),
        ),
    ]
