# Generated by Django 5.0.3 on 2024-04-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventario'},
        ),
    ]
