# Generated by Django 5.0.3 on 2024-04-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventario', '0002_alter_inventario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='Producto',
        ),
    ]
