# Generated by Django 5.0.3 on 2024-04-05 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventario', '0003_remove_inventario_producto'),
        ('control_productos', '0002_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='control_productos.producto'),
            preserve_default=False,
        ),
    ]
