# Generated by Django 5.0.4 on 2024-05-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_compras', '0002_remove_compra_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
