# Generated by Django 5.0.4 on 2024-05-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_compras', '0003_remove_compra_proveedor_alter_compra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='control_compras.compra'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
    ]
