# Generated by Django 5.0.3 on 2024-05-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_productos', '0002_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
